import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { OperatorControlPlane } from "../src/operator-control.js";
import { DurableOperatorSupervisor } from "../src/operator-supervisor.js";
import { BuzzRootDispatchQueue, JsonFileRootDispatchStore } from "../src/root-dispatch.js";
import type { RootDispatchBinding, RootDispatchEnvelope } from "../src/root-dispatch-types.js";

const now = "2026-08-08T12:40:00.000Z";
const key = "agent:down:buzz:supervisor";
const binding: RootDispatchBinding = { binding_id: "down", protocol_version: "0.1", relay: "wss://relay", community_id: "community", openclaw_agent_id: "down", openclaw_session_key: key, openclaw_session_key_sha256: createHash("sha256").update(key).digest("hex"), openclaw_session_id: "existing", allowed_channel_ids: ["engine"], allowed_source_pubkeys: ["aa".repeat(32)], valid_from: now, valid_until: "2026-08-08T13:40:00.000Z", require_existing: true, reset_session: false, status: "active" };
const makeEnvelope = (byte: string): RootDispatchEnvelope => ({ protocol_version: "0.1", source_event_id: byte.repeat(32), thread_root_event_id: byte.repeat(32), source_pubkey: "aa".repeat(32), channel_id: "engine", binding_id: "down", openclaw_agent_id: "down", openclaw_session_key_sha256: binding.openclaw_session_key_sha256, openclaw_session_id: "existing", payload_digest: "bb".repeat(32), role_request_id: null, received_at: now, not_before: now, expires_at: binding.valid_until, execution_posture: "not_executed", authority_transfer: "none" });
const dir = mkdtempSync(join(tmpdir(), "buzz-supervisor-"));
const controlPath = join(dir, "control.json"); const queuePath = join(dir, "queue.json"); const control = new OperatorControlPlane(controlPath);
const queue = new BuzzRootDispatchQueue({ bindings: [binding], operator_control: control, store: new JsonFileRootDispatchStore(queuePath, now), transport: { async dispatch(request) { return { status: "accepted", transport_ref: `turn:${request.envelope.source_event_id}`, accepted_at: now, evidence_refs: [] }; } } });
const outcomes = new Map([["11".repeat(32), "verified"], ["22".repeat(32), "retryable"], ["33".repeat(32), "indeterminate"]]);
const supervisor = new DurableOperatorSupervisor({ queue, control, completion: { async reconcile(id) { const status = outcomes.get(id); if (status === "verified") return { status, proof_ref: `reply:${id}`, verified_at: now }; if (status === "retryable") return { status, code: "relay_unavailable", observed_at: now }; return { status: "indeterminate", code: "publication_unknown", observed_at: now }; } } });
for (const byte of ["11", "22", "33"]) assert.equal(supervisor.accept(makeEnvelope(byte), now).status, "queued");
const result = await supervisor.cycle("down", now);
assert.equal(result.reconciled.length, 1);
assert.equal(result.retryable.length, 1);
assert.equal(result.quarantined.length, 1);
assert.equal(control.get("11".repeat(32))?.disposition, "reconciled");
assert.equal(control.get("22".repeat(32))?.disposition, "retryable");
assert.equal(control.get("33".repeat(32))?.disposition, "quarantined");
const restarted = new OperatorControlPlane(join(dir, "control.json"));
assert.equal(restarted.inspect().records.length, 3);
let recoveredReconciliations = 0; const recoveredQueue = new BuzzRootDispatchQueue({ bindings: [binding], operator_control: restarted, store: new JsonFileRootDispatchStore(queuePath, now), transport: { async dispatch() { throw new Error("must not redispatch"); } } });
const recoveredSupervisor = new DurableOperatorSupervisor({ queue: recoveredQueue, control: restarted, completion: { async reconcile(id) { recoveredReconciliations++; return { status: "verified", proof_ref: `recovered:${id}`, verified_at: now }; } } });
await recoveredSupervisor.cycle("down", now); assert.equal(recoveredReconciliations, 2); assert.equal(restarted.get("22".repeat(32))?.disposition, "reconciled"); assert.equal(restarted.get("33".repeat(32))?.disposition, "reconciled");
rmSync(dir, { recursive: true, force: true });
console.log("1..1\n# 1 operator-supervisor test passed");
